import '.././globals.css';
import { Toaster } from 'react-hot-toast';
import HeaderAdmin from '../components/Admin/Navigation/HeaderAdmin';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function AdminRootLayout({ children }: { children: React.ReactNode }) {
	return (
		<div className='flex-1 flex bg-black/95'>
			<HeaderAdmin />
			<div aria-live='assertive'>
				<Toaster position='top-right' />
			</div>
			{children}
		</div>
	);
}
