import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AuthProvider from './components/AuthProvider/AuthProvider';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en' id='smooth-wrapper' className='scrollbar relative scroll-smooth overflow-x-hidden'>
			<body id='smooth-content' className={`${inter.className} min-h-screen bg-white flex flex-col max-w-[2000px] mx-auto`}>
				<AuthProvider>{children}</AuthProvider>
			</body>
		</html>
	);
}
